version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Navigating to frontend..."
      - cd $CODEBUILD_SRC_DIR/frontend
      - npm install
  build:
    commands:
      - echo "Starting Vite build..."
      - cd $CODEBUILD_SRC_DIR/frontend
      - npm run build
      - echo "Verifying build output..."
      - ls -R dist
artifacts:
  base-directory: frontend/dist
  files:
    - '**/*'
